resources:
- repo: self
queue:
  name: selfhosted@mua

steps:
- powershell : > 
    ./pipelines/runbuild.ps1 -properties @{     
     "publishNugets"=$false;
     "updateAssemblyInfo" = $true;
     "testTargetAmsId" = "172.20.10.2.1.1";
     "isTestingEnabled" = $true
     }   
  displayName: 'Psake build'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Pipeline.Workspace)'
    artifact: 'PublishArtifacts'
    publishLocation: 'pipeline'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'TcoUnitTests'
