resources:
- repo: self
queue:
  name: selfhosted@mua

steps:
- powershell : > 
    ./pipeline/runbuild.ps1 -properties @{
     "msbuild"="`"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe`"";     
     "publishNugets"=$false;
     "updateAssemblyInfo" = $true;
     "testTargetAmsId" = "172.20.10.2.1.1"
     }   
  displayName: 'Psake build'